# Generated by Django 6.0.3 on 2026-06-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='created',
            new_name='published',
        ),
    ]
