# Generated by Django 6.0.3 on 2026-06-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_rename_created_entry_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
